# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

- pool:
  name: default 
  vmImage: nodejs

- steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- step:
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'NodeJS_SonarCloud'
    organization: sohamruz1998
    scannerMode: CLI
    configMode: manual
    cliProjectKey: 'sohamruz1998_NodeJs_Express_Project'
    cliProjectName: 'NodeJs_Express_Project'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- step:
- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
  
- step:
- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
  
- step:
- task: Docker@2
  displayName: build
  inputs:
    containerRegistry: 'Docker_azure'
    repository: sohamruzz/nodejs
    command: build
    Dockerfile: Dockerfile
    addPipelineData: false
    addBaseImageData: false

  

